weather = "rainy"
if weather == "sunny":
    print("wear a sunny dress!!!")
elif weather == "rainy":
    print("wear a rain coat!!!")
else:
    print("wear a sweater")


temperature = 20
if temperature > 18:
    print("it is abv 2 degree celcius")
else:
    print("it is freezing!")

age = 22
if age>20:
  print("it is true")
else:
 print("it is false")

example_line= "   Hello World"
print(example_line.strip())

a_string = "one_two_three,four_five"
tokens = a_string.split(',')
for token in tokens:
   print(token)

times = 0
while times < 5:
   print("hi")
   times -= 1
   print("bye")
  

candies_in_jar = 10

while candies_in_jar > 0:
     print("yum")
     candies_in_jar -= 1

print("oh no")



   
