import turtle

turtle.forward(100)
turtle.left(87)
turtle.setheading(127)
turtle.up()
turtle.down()
turtle.goto(50,50)
turtle.home()
turtle.circle(25)
asdf=turtle.isdown()
quarty=turtle.scor()
werty=turtle.ycor()
print(asdf)
print(quarty)
